const $ = (id) => document.getElementById(id);

export const refs = {
    fileInput: $("fileInput"),
    fileButton: $("fileButton"),
    dropZone: $("dropZone"),
    fileName: $("fileName"),
    durationLabel: $("durationLabel"),
    fileType: $("fileType"),
    sampleRateLabel: $("sampleRateLabel"),
    playBtn: $("playBtn"),
    startBtn: $("startBtn"),
    loopToggleBtn: $("loopToggleBtn"),
    outputLeftBtn: $("outputLeftBtn"),
    outputRightBtn: $("outputRightBtn"),
    undoBtn: $("undoBtn"),
    redoBtn: $("redoBtn"),
    cutBtn: $("cutBtn"),
    copyBtn: $("copyBtn"),
    pasteBtn: $("pasteBtn"),
    trimRangeBtn: $("trimRangeBtn"),
    silenceRangeBtn: $("silenceRangeBtn"),
    duplicateBtn: $("duplicateBtn"),
    silenceBtn: $("silenceBtn"),
    quickNormalizeBtn: $("quickNormalizeBtn"),
    quickFadeInBtn: $("quickFadeInBtn"),
    quickFadeOutBtn: $("quickFadeOutBtn"),
    quickStretchBtn: $("quickStretchBtn"),
    quickPanel: $("quickPanel"),
    quickPanelLabel: $("quickPanelLabel"),
    quickCloseBtn: $("quickCloseBtn"),
    normalizeGainField: $("normalizeGainField"),
    normalizeGainInput: $("normalizeGainInput"),
    fadeCurveField: $("fadeCurveField"),
    quickFadeCurveSelect: $("quickFadeCurveSelect"),
    silenceLengthField: $("silenceLengthField"),
    silenceLengthInput: $("silenceLengthInput"),
    stretchModeField: $("stretchModeField"),
    stretchModeSelect: $("stretchModeSelect"),
    stretchMethodField: $("stretchMethodField"),
    stretchMethodSelect: $("stretchMethodSelect"),
    stretchRatioField: $("stretchRatioField"),
    stretchRatioInput: $("stretchRatioInput"),
    stretchSpeedField: $("stretchSpeedField"),
    stretchSpeedInput: $("stretchSpeedInput"),
    stretchTargetDurationField: $("stretchTargetDurationField"),
    stretchTargetDurationInput: $("stretchTargetDurationInput"),
    stretchFromBpmField: $("stretchFromBpmField"),
    stretchFromBpmInput: $("stretchFromBpmInput"),
    stretchToBpmField: $("stretchToBpmField"),
    stretchToBpmInput: $("stretchToBpmInput"),
    quickPanelHint: $("quickPanelHint"),
    quickApplyBtn: $("quickApplyBtn"),
    waveFrame: $("waveFrame"),
    waveCanvas: $("waveCanvas"),
    clipLayer: $("clipLayer"),
    waveSelection: $("waveSelection"),
    playhead: $("playhead"),
    timeLabel: $("timeLabel"),
    selectionLabel: $("selectionLabel"),
    waveInfo: $("waveInfo"),
    selectionStartInput: $("selectionStartInput"),
    selectionEndInput: $("selectionEndInput"),
    playheadInput: $("playheadInput"),
    vuLeft: $("vuLeft"),
    vuRight: $("vuRight"),
    vuLeftPeak: $("vuLeftPeak"),
    vuRightPeak: $("vuRightPeak"),
    vuLeftLabel: $("vuLeftLabel"),
    vuRightLabel: $("vuRightLabel"),
    trackVolumeRange: $("trackVolumeRange"),
    trackVolumeInput: $("trackVolumeInput"),
    trackPanRange: $("trackPanRange"),
    trackPanInput: $("trackPanInput"),
    centerPanBtn: $("centerPanBtn"),
    effectPicker: $("effectPicker"),
    effectPickerBtn: $("effectPickerBtn"),
    effectMenu: $("effectMenu"),
    effectsList: $("effectsList"),
    exportFormatSelect: $("exportFormatSelect"),
    exportSampleRateSelect: $("exportSampleRateSelect"),
    exportChannelSelect: $("exportChannelSelect"),
    exportBitDepthField: $("exportBitDepthField"),
    exportBitDepthSelect: $("exportBitDepthSelect"),
    exportBitrateField: $("exportBitrateField"),
    exportBitrateSelect: $("exportBitrateSelect"),
    exportIncludeTailCheckbox: $("exportIncludeTailCheckbox"),
    exportBtn: $("exportBtn"),
    exportStatus: $("exportStatus"),
    statusDot: $("statusDot"),
    statusText: $("statusText"),
};

export const editControls = [
    refs.playBtn,
    refs.startBtn,
    refs.loopToggleBtn,
    refs.outputLeftBtn,
    refs.outputRightBtn,
    refs.cutBtn,
    refs.copyBtn,
    refs.silenceRangeBtn,
    refs.trimRangeBtn,
    refs.duplicateBtn,
    refs.silenceBtn,
    refs.quickNormalizeBtn,
    refs.quickFadeInBtn,
    refs.quickFadeOutBtn,
    refs.quickStretchBtn,
    refs.selectionStartInput,
    refs.selectionEndInput,
    refs.playheadInput,
    refs.trackVolumeRange,
    refs.trackVolumeInput,
    refs.trackPanRange,
    refs.trackPanInput,
    refs.centerPanBtn,
    refs.effectPickerBtn,
    refs.exportFormatSelect,
    refs.exportSampleRateSelect,
    refs.exportChannelSelect,
    refs.exportBitDepthSelect,
    refs.exportBitrateSelect,
    refs.exportIncludeTailCheckbox,
    refs.exportBtn,
];
