export const EXPORT_TAIL_MAX_SECONDS = 60;
export const EXPORT_TAIL_SILENCE_SECONDS = 1.5;
export const EXPORT_TAIL_THRESHOLD_DB = -80;
export const EXPORT_TAIL_ANALYSIS_WINDOW_SECONDS = 0.05;
export const SELECTION_HANDLE_HIT_PX = 10;
